Repository MicrosoftDocs/powerbi-docs.zh-cn, pull requests merged in 2020-05, with the labels that each got.

#60 Update end-user-home.md
  powerbi-docs/consumer/end-user-home.md
Labels: Linguistic Suggestion, P1, Partially Accepted

#62 Update service-new-look-where-actions.md
  powerbi-docs/service-new-look-where-actions.md
Labels: Accepted, Linguistic Suggestion, P1

#61 Update service-service-vs-desktop.md
  powerbi-docs/fundamentals/service-service-vs-desktop.md
Labels: Accepted, Linguistic Suggestion

#66 Deskop -> Desktop
  powerbi-docs/create-reports/desktop-export-to-pdf.md
Labels: Accepted, Linguistic Suggestion, P1

#68 Correct the method name
  powerbi-docs/developer/automation/walkthrough-push-data-get-datasets.md
Labels: Accepted, Linguistic Suggestion, P1

#69 Update power-bi-visualization-kpi.md
  powerbi-docs/visuals/power-bi-visualization-kpi.md
Labels: Linguistic Suggestion, P1, Partially Accepted

#64 Fixed minor typos
  powerbi-docs/admin/service-admin-premium-purchase.md
  powerbi-docs/admin/service-admin-where-is-my-tenant-located.md
Labels: Accepted, Linguistic Suggestion, P1

#67 Powre -> Power
  powerbi-docs/transform-model/desktop-ai-insights.md
  powerbi-docs/transform-model/service-machine-learning-integration.md
Labels: Accepted, Linguistic Suggestion, P1
